Name : Jackel website CI: Jackel Website CI



    Branch: [   "Pinxin Winery"   ]

    Branch: [   "Text"   ]




    Run at: ubuntu-latest

enter:
    -Purpose : actions/checkout@v4
    -Name : Build a website in jekyll/builder container
      Run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
